### ISSUE TITLE
On Android version less than 6 (M) checkPermissionStatus returns Denied

### ISSUE THREAD

**Issue by orteney** [Baseflow/flutter-permission-plugins#60]
## 🐛 Bug Report

Method `checkPermissionStatus` on Android without runtime permissions (pre M) always **Denied** but actually it should be **Granted** as permissions are given during installation.

**Version:** 4.0.0

**Platform:** [5.0.2] :robot: Android

**Comment by FogNature** [comment]
Same issue, but not only on pre M devices.

**Comment by randyachmad** [comment]
Any solution? I faced same issue rn on Android 11

**Comment by mvanbeusekom** [comment]
@fognature and @randyachmad, this issue is specifically about devices without runtime permissions (pre Android M). If you experience issues with later devices please create a new issue and provide the following details:

- Clear description of the problem (including reproduction steps);
- Output of the `flutter doctor -v` command;
- Contents of your `android/app/src/main/AndroidManifest.xml` file (this should include the permissions you are requesting, see also the Android section of the [README.md](https://pub.dev/packages/permission_handler)).

**Comment by mvanbeusekom** [comment]
P.S. the `location_permissions` plugin is no longer maintained and is replaced with the `permission_handler` plugin.
